### ISSUE TITLE
Implement Signup page

### ISSUE THREAD

**Issue by SrijaAdhya12** [Jagroop2001/Pages-A-Book-Shop-Website#11]
- Users need to sign up with their details before signing in.
- I want to implement a fully responsive signup page with the following fields: 
  1. First Name
  2. Last Name
  3. Email
  4. Phone Number
  5. Avatar/Profile Picture
  6. Password
  7. Repeat Password
  8. Username
- Signup Button
- Form Validations
- Signup using OAuth apps (Google, Facebook, Microsoft, Apple)

**Comment by jagroop-dev-11** [comment]
@SrijaAdhya12 ,
go for it.
**For this please cover below points only :** 
Users need to sign up with their details before signing in.
I want to implement a fully responsive signup page with the following fields:
- First Name
- Last Name
- Email
- Phone Number
- Password
- Repeat Password
- Username
- Signup Button
- Form Validations

For now, let's us either to store in json or firebase.
