### ISSUE TITLE
Adding contact details like email, location of the company, and adding details in the ABOUT and SERVICES section.

### ISSUE THREAD

**Issue by trinetra110** [Jagroop2001/Pages-A-Book-Shop-Website#8]
We can add contact details like email and the location of the company so that anyone can reach out to us, apart from the social media handles. We should also add pages that have the ABOUT section so that it signifies how our website works and our journey. The SERVICES section can be added to give information about what kind of services we provide, etc.

**Comment by jagroop-dev-11** [comment]
@trinetra110 ,
go for it.

**Comment by jagroop-dev-11** [comment]
https://github.com/Jagroop2001/Pages-A-Book-Shop-Website/pull/17
